### ISSUE TITLE
Test doesn't work

### ISSUE THREAD

**Issue by joeynuggetz** [jneilliii/OctoPrint-M117SpeechSynthesis#1]
Tried in Chrome and in Edge. Voices listed but no audio. Firefox does not list any available voices.

**Comment by jneilliii** [comment]
Are there any errors in the browser's console?

**Comment by markwdickson** [comment]
I found that the "Test" button is disabled when first enabling the plugin. When you click the checkbox "Enable Speech" you must first click the "Save" button at the bottom to update the changes.  THEN go back into the settings again and the Test button will be active.  Could this be your problem?

I was going to suggest making the Test button active upon clicking the "Enable Speech" checkbox rather than having to Save the settings and re-enter the dialog again. I too thought something was broken before I realized it was an order of events thing.

**Comment by jneilliii** [comment]
That is actually how it's currently programmed. I have an idea to get around that implementation for a future release, but haven't had the time to program and test. Disabling the test button was a workaround to force a save because of what I think is a knockout binding issue on my end.

**Comment by jneilliii** [comment]
Logic updated in latest release 0.4.0 addressing @markwdickson concern, closing since no response from @joeynuggetz
